set(_CATKIN_CURRENT_PACKAGE "floor_plane_mapping")
set(floor_plane_mapping_MAINTAINER "cedricp <cedric.pradalier@georgiatech-metz.fr>")
set(floor_plane_mapping_DEPRECATED "")
set(floor_plane_mapping_VERSION "0.1.0")
set(floor_plane_mapping_BUILD_DEPENDS "roscpp" "pcl_ros" "sensor_msgs" "tf" "visualization_msgs" "message_generation")
set(floor_plane_mapping_RUN_DEPENDS "roscpp" "pcl_ros" "sensor_msgs" "tf" "visualization_msgs" "message_runtime")
set(floor_plane_mapping_BUILDTOOL_DEPENDS "catkin")